// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADd2NNCfs-zKHxjDf7pJLU7tbcESlYuow',
    appId: '1:554026799851:web:f41bdf90e9d0e02456a4ae',
    messagingSenderId: '554026799851',
    projectId: 'firestore-f7350',
    authDomain: 'firestore-f7350.firebaseapp.com',
    storageBucket: 'firestore-f7350.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfftWfpLwb1bPPau9J0Ph-d05SKkjlBzg',
    appId: '1:554026799851:android:332503676379207b56a4ae',
    messagingSenderId: '554026799851',
    projectId: 'firestore-f7350',
    storageBucket: 'firestore-f7350.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmFLQHsjYPlrMtvYh_vgFsMH2ayvSC1jk',
    appId: '1:554026799851:ios:2b9a1985f6b6bee156a4ae',
    messagingSenderId: '554026799851',
    projectId: 'firestore-f7350',
    storageBucket: 'firestore-f7350.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmFLQHsjYPlrMtvYh_vgFsMH2ayvSC1jk',
    appId: '1:554026799851:ios:2b9a1985f6b6bee156a4ae',
    messagingSenderId: '554026799851',
    projectId: 'firestore-f7350',
    storageBucket: 'firestore-f7350.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADd2NNCfs-zKHxjDf7pJLU7tbcESlYuow',
    appId: '1:554026799851:web:1a83be0924d2405056a4ae',
    messagingSenderId: '554026799851',
    projectId: 'firestore-f7350',
    authDomain: 'firestore-f7350.firebaseapp.com',
    storageBucket: 'firestore-f7350.firebasestorage.app',
  );
}
